from __future__ import annotations

import os
import platform
import shutil


SYSTEM_INFO_START = "--- hey autogenerated system info ---"
SYSTEM_INFO_END = "--- end hey autogenerated system info ---"

SYSTEM_PACKAGE_MANAGERS = (
    "brew",
    "port",
    "apt",
    "apt-get",
    "dnf",
    "yum",
    "pacman",
    "zypper",
    "apk",
    "emerge",
    "xbps-install",
    "nix",
    "nix-env",
    "guix",
    "snap",
    "flatpak",
    "dpkg",
    "rpm",
)
DEVELOPER_PACKAGE_TOOLS = (
    "pip3",
    "pip",
    "pipx",
    "uv",
    "npm",
    "pnpm",
    "yarn",
    "bun",
    "cargo",
    "gem",
    "composer",
)
SERVICE_MANAGERS = (
    "systemctl",
    "service",
    "launchctl",
    "rc-service",
    "svcadm",
)
PRIVILEGE_TOOLS = (
    "sudo",
    "doas",
    "su",
)


def build_system_info() -> str:
    lines = [
        SYSTEM_INFO_START,
        "You can edit this section. Reset it anytime with: hey --refresh-system-info",
        f"Operating system: {_operating_system()}",
        f"Kernel: {_kernel()}",
        f"Architecture: {_architecture()}",
        f"Shell: {_shell()}",
        f"System package managers: {_found_commands(SYSTEM_PACKAGE_MANAGERS)}",
        f"Developer package tools: {_found_commands(DEVELOPER_PACKAGE_TOOLS)}",
        f"Service managers: {_found_commands(SERVICE_MANAGERS)}",
        f"Privilege tools: {_found_commands(PRIVILEGE_TOOLS)}",
        SYSTEM_INFO_END,
    ]
    return "\n".join(lines)


def _operating_system() -> str:
    system = platform.system()
    if system == "Darwin":
        version, _, _ = platform.mac_ver()
        return f"macOS {version or 'unknown version'}"
    if system == "Linux":
        return _linux_pretty_name() or "Linux"

    release = platform.release()
    if system and release:
        return f"{system} {release}"
    return system or "unknown"


def _linux_pretty_name() -> str | None:
    try:
        values = platform.freedesktop_os_release()
    except OSError:
        return None
    return values.get("PRETTY_NAME") or values.get("NAME")


def _kernel() -> str:
    system = platform.system() or "unknown"
    release = platform.release() or "unknown"
    version = platform.version() or "unknown"
    return f"{system} {release} ({version})"


def _architecture() -> str:
    return platform.machine() or "unknown"


def _shell() -> str:
    shell = os.environ.get("SHELL")
    if not shell:
        return "unknown"
    return os.path.basename(shell) or shell


def _found_commands(candidates: tuple[str, ...]) -> str:
    found = [name for name in candidates if shutil.which(name)]
    return ", ".join(found) if found else "none detected in PATH"
